import { describe, expect, test } from "bun:test"
import { Schema } from "effect"
import { Agent } from "../src/agent"
import { FileSystem } from "../src/filesystem"
import { Admission } from "../src/lifecycle/admission"
import { Cancel } from "../src/lifecycle/cancel"
import { CorrelationIds } from "../src/lifecycle/correlation-ids"
import { Enums } from "../src/lifecycle/enums"
import { EnumsObservation } from "../src/lifecycle/enums-observation"
import { Envelope } from "../src/lifecycle/envelope"
import { Events as LifecycleEvent } from "../src/lifecycle/events"
import { Ids as LifecycleIds } from "../src/lifecycle/ids"
import { Observation } from "../src/lifecycle/observation"
import { Row } from "../src/lifecycle/process-row"
import { RowParts } from "../src/lifecycle/process-row-parts"
import { TodoEvents } from "../src/lifecycle/todo-events"
import { Usage } from "../src/lifecycle/usage"
import { UsageValues } from "../src/lifecycle/usage-values"
import { Values } from "../src/lifecycle/values"
import { Watchdog } from "../src/lifecycle/watchdog"
import { Model } from "../src/model"
import { Project } from "../src/project"
import { Pty } from "../src/pty"
import { Question } from "../src/question"
import { Budget } from "../src/routing/budget"
import { Capability } from "../src/routing/capability"
import { RoutingConfig } from "../src/routing/config"
import { Decision } from "../src/routing/decision"
import { Events } from "../src/routing/events"
import { Ids } from "../src/routing/ids"
import { Session } from "../src/session"
import { SessionEvent } from "../src/session-event"
import { SessionTodo } from "../src/session-todo"
import { Config as TelemetryConfig } from "../src/telemetry/config"
import { SmartState } from "../src/tui/smart-state"
import { Correlation as JobsCorrelation } from "../src/jobs/correlation"
import { Definition as JobsDefinition } from "../src/jobs/definition"
import { Enums as JobsEnums } from "../src/jobs/enums"
import { EnumsEvent as JobsEnumsEvent } from "../src/jobs/enums-event"
import { EnumsNotification as JobsEnumsNotification } from "../src/jobs/enums-notification"
import { Envelope as JobsEnvelope } from "../src/jobs/envelope"
import { Events as JobsEvents } from "../src/jobs/events"
import { EventTypes as JobsEventTypes } from "../src/jobs/event-types"
import { Ids as JobsIds } from "../src/jobs/ids"
import { Notification as JobsNotification } from "../src/jobs/notification"
import { Occurrence as JobsOccurrence } from "../src/jobs/occurrence"
import { Reconciliation as JobsReconciliation } from "../src/jobs/reconciliation"
import { Schedule as JobsSchedule } from "../src/jobs/schedule"
import { TextValues as JobsTextValues } from "../src/jobs/text-values"
import { Values as JobsValues } from "../src/jobs/values"
import { Allowlist as LangLockAllowlist } from "../src/langlock/allowlist"
import { Config as LangLockConfig } from "../src/langlock/config"
import { Correlation as LangLockCorrelation } from "../src/langlock/correlation"
import { Detection as LangLockDetection } from "../src/langlock/detection"
import { Effective as LangLockEffective } from "../src/langlock/effective"
import { Enums as LangLockEnums } from "../src/langlock/enums"
import { EnumsEvent as LangLockEnumsEvent } from "../src/langlock/enums-event"
import { Envelope as LangLockEnvelope } from "../src/langlock/envelope"
import { Events as LangLockEvents } from "../src/langlock/events"
import { EventTypes as LangLockEventTypes } from "../src/langlock/event-types"
import { ExecutionEnvelope as LangLockExecution } from "../src/langlock/execution-envelope"
import { Exception as LangLockException } from "../src/langlock/exception"
import { Ids as LangLockIds } from "../src/langlock/ids"
import { Policy as LangLockPolicy } from "../src/langlock/policy"
import { TextValues as LangLockTextValues } from "../src/langlock/text-values"
import { Values as LangLockValues } from "../src/langlock/values"
import { Admin as OutputSpoolAdmin } from "../src/outputspool/admin"
import { Channel as OutputSpoolChannel } from "../src/outputspool/channel"
import { Correlation as OutputSpoolCorrelation } from "../src/outputspool/correlation"
import { Cursor as OutputSpoolCursor } from "../src/outputspool/cursor"
import { Enums as OutputSpoolEnums } from "../src/outputspool/enums"
import { EnumsEvent as OutputSpoolEnumsEvent } from "../src/outputspool/enums-event"
import { Envelope as OutputSpoolEnvelope } from "../src/outputspool/envelope"
import { Events as OutputSpoolEvents } from "../src/outputspool/events"
import { EventTypes as OutputSpoolEventTypes } from "../src/outputspool/event-types"
import { Group as OutputSpoolGroup } from "../src/outputspool/group"
import { Ids as OutputSpoolIds } from "../src/outputspool/ids"
import { Page as OutputSpoolPage } from "../src/outputspool/page"
import { Preview as OutputSpoolPreview } from "../src/outputspool/preview"
import { Quota as OutputSpoolQuota } from "../src/outputspool/quota"
import { Retention as OutputSpoolRetention } from "../src/outputspool/retention"
import { Stat as OutputSpoolStat } from "../src/outputspool/stat"
import { TextValues as OutputSpoolTextValues } from "../src/outputspool/text-values"
import { Values as OutputSpoolValues } from "../src/outputspool/values"
import { Binding as SemanticBinding } from "../src/semantic/binding"
import { Collections as SemanticCollections } from "../src/semantic/collections"
import { Correlation as SemanticCorrelation } from "../src/semantic/correlation"
import { Documents as SemanticDocuments } from "../src/semantic/documents"
import { Enums as SemanticEnums } from "../src/semantic/enums"
import { EnumsEvent as SemanticEnumsEvent } from "../src/semantic/enums-event"
import { EnumsState as SemanticEnumsState } from "../src/semantic/enums-state"
import { Envelope as SemanticEnvelope } from "../src/semantic/envelope"
import { Events as SemanticEvents } from "../src/semantic/events"
import { EventTypes as SemanticEventTypes } from "../src/semantic/event-types"
import { Ids as SemanticIds } from "../src/semantic/ids"
import { IndexGeneration as SemanticIndexGeneration } from "../src/semantic/index-generation"
import { ModelDescriptor as SemanticModelDescriptor } from "../src/semantic/model-descriptor"
import { Profile as SemanticProfile } from "../src/semantic/profile"
import { ProviderProfile as SemanticProviderProfile } from "../src/semantic/provider-profile"
import { Refs as SemanticRefs } from "../src/semantic/refs"
import { Retrieval as SemanticRetrieval } from "../src/semantic/retrieval"
import { TextValues as SemanticTextValues } from "../src/semantic/text-values"
import {
  ToolDescriptor as SemanticToolDescriptor,
  ToolDoc as SemanticToolDoc,
  ToolParameter as SemanticToolParameter,
  ToolParameterProjection as SemanticToolParameterProjection,
} from "../src/semantic/tool-doc"
import {
  ToolSearchConfig as SemanticToolSearchConfig,
  ToolSurfaceConfig as SemanticToolSurfaceConfig,
} from "../src/semantic/tool-config"
import { Values as SemanticValues } from "../src/semantic/values"
import { Capability as McpCapability } from "../src/mcp/capability"
import { Collections as McpCollections } from "../src/mcp/collections"
import { Connection as McpConnection } from "../src/mcp/connection"
import { Enums as McpEnums } from "../src/mcp/enums"
import { EnumsEvent as McpEnumsEvent } from "../src/mcp/enums-event"
import { EnumsState as McpEnumsState } from "../src/mcp/enums-state"
import { Envelope as McpEnvelope } from "../src/mcp/envelope"
import { Events as McpEvents } from "../src/mcp/events"
import { EventsCall as McpEventsCall } from "../src/mcp/events-call"
import { EventsLive as McpEventsLive } from "../src/mcp/events-live"
import { EventsLog as McpEventsLog } from "../src/mcp/events-log"
import { EventsResource as McpEventsResource } from "../src/mcp/events-resource"
import { EventsServer as McpEventsServer } from "../src/mcp/events-server"
import { EventTypes as McpEventTypes } from "../src/mcp/event-types"
import { Experimental as McpExperimental } from "../src/mcp/experimental"
import { Ids as McpIds } from "../src/mcp/ids"
import { Policy as McpPolicy } from "../src/mcp/policy"
import { Refs as McpRefs } from "../src/mcp/refs"
import { SpoolDescriptor as McpSpoolDescriptor } from "../src/mcp/spool-descriptor"
import { TextValues as McpTextValues } from "../src/mcp/text-values"
import { Uri as McpUri } from "../src/mcp/uri"
import { Allowlist as McpAllowlist } from "../src/mcp/uri-allowlist"
import { Values as McpValues } from "../src/mcp/values"
import { optional } from "../src/schema"

describe("contract hygiene", () => {
  test("optional properties preserve transformations and omit undefined while encoding", () => {
    const Value = Schema.Struct({ value: optional(Schema.FiniteFromString) })
    expect(Schema.decodeUnknownSync(Value)({ value: "1" })).toEqual({ value: 1 })
    expect(Schema.encodeSync(Value)({ value: 1 })).toEqual({ value: "1" })
    expect(Schema.encodeSync(Value)({ value: undefined })).toEqual({})
  })

  test("todo status and priority preserve arbitrary strings", () => {
    const decode = Schema.decodeUnknownSync(SessionTodo.Info)
    expect(decode({ content: "ship", status: "waiting", priority: "urgent" })).toEqual({
      content: "ship",
      status: "waiting",
      priority: "urgent",
    })
  })

  test("current ID constructors expose create", () => {
    expect(Question.ID.create()).toStartWith("que_")
    expect(Pty.ID.create()).toStartWith("pty_")
  })

  test("reusable public identifiers are stable and unique", () => {
    const identifiers = [
      Agent.Color,
      FileSystem.Submatch,
      Model.Ref,
      Model.Capabilities,
      Model.Cost,
      Model.Api,
      Project.Icon,
      Project.Commands,
      Project.Time,
      Project.Info,
      Pty.Info,
      Session.ListAnchor,
      Ids.Reason,
      Ids.Requirement,
      Ids.Version,
      Capability.ToolCallDimensions,
      Capability.Identity,
      Capability.Confidence,
      Capability.Assessment,
      Capability.Freshness,
      Capability.Record,
      Capability.Mismatch,
      Decision.GatePassed,
      Decision.CandidateRejected,
      Decision.TieBreakApplied,
      Decision.FallbackAttempted,
      Decision.Offline,
      Decision.GateResult,
      Decision.GateList,
      Decision.SkillList,
      Decision.CandidateIdentity,
      Decision.CandidateProfile,
      Decision.CandidateOutcome,
      Decision.CandidateRecord,
      Decision.RankedCandidate,
      Decision.RankingList,
      Decision.AuthContextSnapshot,
      Decision.ExpectedTools,
      Decision.InputStructure,
      Decision.InputRisk,
      Decision.InputConcurrency,
      Decision.DecisionInputs,
      Decision.DecisionOutput,
      Decision.DecisionContext,
      Decision.DecisionClassification,
      Decision.DecisionSelection,
      Decision.DecisionEvaluation,
      Decision.DecisionAccounting,
      Decision.DecisionLifecycle,
      Decision.RoutingDecision,
      Events.DecisionCorrelation,
      Events.EventClassification,
      Events.EventSelection,
      Events.DispatchLineage,
      Events.DispatchFanout,
      Events.TodoPointer,
      Events.EvidenceRefs,
      Events.RoutingDecisionEvent,
      Events.RoutingFallbackEvent,
      Events.HierarchyDispatchEvent,
      Events.HierarchyValidationEvent,
      Events.HierarchyEscalationEvent,
      Events.CapabilityMismatchEvent,
      Events.TodoInitializedEvent,
      Events.TodoCompletionBlockedEvent,
      Events.RoutingEvent,
      Budget.Limits,
      Budget.Concurrency,
      Budget.Retrieval,
      Budget.Cost,
      Budget.Resilience,
      Budget.Policy,
      Budget.Scope,
      Budget.PolicySnapshot,
      Budget.ConsumptionThroughput,
      Budget.ConsumptionConcurrency,
      Budget.ConsumptionRetrieval,
      Budget.ConsumptionCost,
      Budget.ConsumptionResilience,
      Budget.Consumption,
      RoutingConfig.Activation,
      RoutingConfig.Models,
      RoutingConfig.Enforcement,
      RoutingConfig.Info,
      TelemetryConfig.SecretRef,
      TelemetryConfig.ExportTarget,
      TelemetryConfig.TelemetryConfig,
      SmartState.Active,
      SmartState.Inactive,
      Admission.CapacitySignals,
      Admission.TokenBucketState,
      Admission.AdmissionBucket,
      Admission.AdmissionResult,
      Cancel.RootCancelScope,
      Cancel.CancelRequestRecord,
      CorrelationIds.CorrelationId,
      CorrelationIds.CausationId,
      CorrelationIds.DecisionId,
      CorrelationIds.TurnId,
      CorrelationIds.AgentName,
      CorrelationIds.ModelId,
      CorrelationIds.ProviderName,
      CorrelationIds.VariantName,
      CorrelationIds.TodoRef,
      CorrelationIds.TodoVersion,
      Enums.ProcessState,
      Enums.LifecycleEventType,
      Enums.EventClass,
      Enums.TerminalReason,
      Enums.SettlementState,
      Enums.Visibility,
      Enums.AgentKind,
      Enums.ActorKind,
      EnumsObservation.UsageProvenance,
      EnumsObservation.UsageSource,
      EnumsObservation.ActivityKind,
      EnumsObservation.HierarchyRole,
      EnumsObservation.ValidationOutcome,
      EnumsObservation.AnomalyKind,
      EnumsObservation.CancelOutcome,
      EnumsObservation.WatchdogOutcome,
      EnumsObservation.AdmissionScope,
      EnumsObservation.AdmissionDecision,
      EnumsObservation.ObservationKind,
      Envelope.EventKind,
      Envelope.TreeIdentity,
      Envelope.ProcessIdentity,
      Envelope.Ordering,
      Envelope.Delivery,
      Envelope.Delegation,
      Envelope.HierarchyCorrelation,
      Envelope.HierarchyContext,
      Envelope.LifecycleEnvelope,
      LifecycleEvent.AdmissionDetail,
      LifecycleEvent.HandoffEndpoint,
      LifecycleEvent.HandoffDetail,
      LifecycleEvent.TerminalDetail,
      LifecycleEvent.WatchdogDetail,
      LifecycleEvent.ToolActivityDetail,
      LifecycleEvent.SteerDetail,
      LifecycleEvent.ReconcileDetail,
      LifecycleEvent.AdmittedEvent,
      LifecycleEvent.ParentAttachedEvent,
      LifecycleEvent.ProcessCreatedEvent,
      LifecycleEvent.StartedEvent,
      LifecycleEvent.HandoffEvent,
      LifecycleEvent.ReconciledEvent,
      LifecycleEvent.CompletedEvent,
      LifecycleEvent.FailedEvent,
      LifecycleEvent.CancelledEvent,
      LifecycleEvent.ZombieDetectedEvent,
      LifecycleEvent.OwnerLostEvent,
      LifecycleEvent.QueuedEvent,
      LifecycleEvent.WaitingEvent,
      LifecycleEvent.PromotedEvent,
      LifecycleEvent.ExtendedEvent,
      LifecycleEvent.TurnStartedEvent,
      LifecycleEvent.TurnEndedEvent,
      LifecycleEvent.TurnFailedEvent,
      LifecycleEvent.UnknownEvent,
      LifecycleEvent.SteerRequestedEvent,
      LifecycleEvent.SteerAcceptedEvent,
      LifecycleEvent.SteerRejectedEvent,
      LifecycleEvent.CancelRequestedEvent,
      LifecycleEvent.CancellingEvent,
      LifecycleEvent.ToolCalledEvent,
      LifecycleEvent.ToolSettledEvent,
      LifecycleEvent.LifecycleEvent,
      LifecycleIds.TaskId,
      LifecycleIds.ProcessId,
      LifecycleIds.ParentProcessId,
      LifecycleIds.RootProcessId,
      LifecycleIds.SessionId,
      LifecycleIds.ParentSessionId,
      LifecycleIds.RootSessionId,
      LifecycleIds.RuntimeInstanceId,
      LifecycleIds.LeaseId,
      LifecycleIds.EventId,
      Observation.ObservationScope,
      Observation.ObservationFilter,
      Observation.AnomalyRecord,
      Observation.ObservationResult,
      Row.RowIdentity,
      Row.RowStatus,
      Row.RowHierarchy,
      Row.ProcessRow,
      RowParts.RowRelations,
      RowParts.RowOwnership,
      RowParts.RowGraph,
      RowParts.RowLineage,
      RowParts.RowClassification,
      RowParts.RowModel,
      RowParts.RowProfile,
      RowParts.RowUsage,
      RowParts.RowOutcome,
      RowParts.RowTelemetry,
      RowParts.RowAccounting,
      TodoEvents.TodoPointer,
      TodoEvents.TodoCounts,
      TodoEvents.TodoUpdatedEvent,
      TodoEvents.TodoCompletedEvent,
      TodoEvents.TodoFailedEvent,
      TodoEvents.TodoCancelledEvent,
      TodoEvents.TodoStaleEvent,
      TodoEvents.TodoRehydratedEvent,
      TodoEvents.TodoHandoffAttachedEvent,
      TodoEvents.TodoEvent,
      Usage.TokenBreakdown,
      Usage.UsageProvenanceMark,
      Usage.LiveUsage,
      UsageValues.TokenCount,
      UsageValues.CostUsd,
      UsageValues.ElapsedMs,
      UsageValues.DurationMs,
      UsageValues.TokensPerSecond,
      UsageValues.TraceId,
      UsageValues.SpanId,
      UsageValues.OutputRef,
      UsageValues.Cursor,
      UsageValues.Confidence,
      Values.Sequence,
      Values.Attempt,
      Values.Generation,
      Values.SchemaVersion,
      Values.DelegationDepth,
      Values.FanoutCount,
      Values.ItemCount,
      Values.Reason,
      Values.Description,
      Values.ActivityLabel,
      Watchdog.WatchdogLease,
      Watchdog.ZombieAssessment,
      Watchdog.ReconcileRecord,
      JobsIds.JobDefinitionId,
      JobsIds.ScheduleId,
      JobsIds.OccurrenceId,
      JobsIds.ProcessId,
      JobsIds.RootProcessId,
      JobsIds.SessionId,
      JobsIds.ParentSessionId,
      JobsIds.RootSessionId,
      JobsIds.NotificationId,
      JobsIds.EventId,
      JobsCorrelation.CorrelationId,
      JobsCorrelation.CausationId,
      JobsCorrelation.DecisionId,
      JobsCorrelation.TurnId,
      JobsCorrelation.Principal,
      JobsCorrelation.SecretRef,
      JobsCorrelation.PayloadRef,
      JobsCorrelation.OutputRef,
      JobsCorrelation.ProjectRef,
      JobsCorrelation.TodoRef,
      JobsValues.Sequence,
      JobsValues.Attempt,
      JobsValues.Generation,
      JobsValues.SchemaVersion,
      JobsValues.Version,
      JobsValues.DeadlineMs,
      JobsValues.TimeoutMs,
      JobsValues.RetryBudget,
      JobsValues.Priority,
      JobsValues.ScheduleLagMs,
      JobsTextValues.JobName,
      JobsTextValues.JobDescription,
      JobsTextValues.ActionTarget,
      JobsTextValues.BoundedSummary,
      JobsTextValues.Reason,
      JobsTextValues.TraceId,
      JobsTextValues.SpanId,
      JobsTextValues.Enabled,
      JobsTextValues.PermissionSet,
      JobsSchedule.CronExpression,
      JobsSchedule.IanaTimezone,
      JobsSchedule.MinimumIntervalMs,
      JobsSchedule.NominalDueTime,
      JobsSchedule.CronSchedule,
      JobsEnums.RegistrationState,
      JobsEnums.RegistrationIntent,
      JobsEnums.OccurrenceState,
      JobsEnums.MisfirePolicy,
      JobsEnums.OverlapPolicy,
      JobsEnums.ActionType,
      JobsEnums.Scope,
      JobsEnums.CapabilitySurface,
      JobsEnums.ReconcileOutcome,
      JobsEnums.EventClass,
      JobsEnumsEvent.JobSource,
      JobsEnumsEvent.ActorKind,
      JobsEnumsEvent.Visibility,
      JobsEnumsNotification.NotificationType,
      JobsEnumsNotification.NotificationPriority,
      JobsEnumsNotification.NotificationSource,
      JobsEnumsNotification.DeliveryState,
      JobsEnumsNotification.AckState,
      JobsEnumsNotification.DeliveryAction,
      JobsEnumsNotification.SafeBoundary,
      JobsEventTypes.JobEventType,
      JobsEnvelope.EventKind,
      JobsEnvelope.OccurrenceIdentity,
      JobsEnvelope.TreeIdentity,
      JobsEnvelope.Ordering,
      JobsEnvelope.Delivery,
      JobsEnvelope.JobEnvelope,
      JobsDefinition.SecretRefList,
      JobsDefinition.DefinitionIdentity,
      JobsDefinition.DefinitionSchedule,
      JobsDefinition.DefinitionPolicy,
      JobsDefinition.DefinitionExecution,
      JobsDefinition.DefinitionAuthorization,
      JobsDefinition.JobDefinition,
      JobsReconciliation.ScheduleRegistration,
      JobsReconciliation.OccurrenceReconcile,
      JobsReconciliation.RegistrationReconcile,
      JobsOccurrence.IdempotencyKey,
      JobsOccurrence.OccurrenceLineage,
      JobsOccurrence.OccurrenceExecution,
      JobsOccurrence.OccurrenceStatus,
      JobsOccurrence.JobOccurrence,
      JobsNotification.NotificationRouting,
      JobsNotification.NotificationDescriptor,
      JobsNotification.NotificationTiming,
      JobsNotification.NotificationContent,
      JobsNotification.NotificationState,
      JobsNotification.NotificationEnvelope,
      JobsEvents.DefinitionDetail,
      JobsEvents.RegistrationDetail,
      JobsEvents.TriggerDetail,
      JobsEvents.MisfireDetail,
      JobsEvents.OverlapDetail,
      JobsEvents.ExecutionDetail,
      JobsEvents.RetryDetail,
      JobsEvents.NotificationDetail,
      JobsEvents.ReconcileDetail,
      JobsEvents.JobDefinitionCreatedEvent,
      JobsEvents.JobDefinitionUpdatedEvent,
      JobsEvents.JobDefinitionEnabledEvent,
      JobsEvents.JobDefinitionDisabledEvent,
      JobsEvents.JobDefinitionDeletedEvent,
      JobsEvents.JobRegisteredEvent,
      JobsEvents.JobUnregisteredEvent,
      JobsEvents.JobRescheduledEvent,
      JobsEvents.JobTriggerDueEvent,
      JobsEvents.JobOccurrenceClaimedEvent,
      JobsEvents.JobTriggeredEvent,
      JobsEvents.JobMisfiredEvent,
      JobsEvents.JobSkippedEvent,
      JobsEvents.JobCoalescedEvent,
      JobsEvents.JobQueuedEvent,
      JobsEvents.JobAdmittedEvent,
      JobsEvents.JobNotificationEnqueuedEvent,
      JobsEvents.JobNotificationDeliveredEvent,
      JobsEvents.JobNotificationAcknowledgedEvent,
      JobsEvents.JobNotificationExpiredEvent,
      JobsEvents.JobExecutionStartedEvent,
      JobsEvents.JobExecutionCompletedEvent,
      JobsEvents.JobExecutionFailedEvent,
      JobsEvents.JobExecutionCancelledEvent,
      JobsEvents.JobExecutionTimedOutEvent,
      JobsEvents.JobRetryScheduledEvent,
      JobsEvents.JobOverlapRejectedEvent,
      JobsEvents.JobOverlapReplacedEvent,
      JobsEvents.JobReconciledEvent,
      JobsEvents.JobUnknownEvent,
      JobsEvents.JobEvent,
      LangLockIds.LanguageTag,
      LangLockIds.PolicyId,
      LangLockIds.ExceptionId,
      LangLockIds.ExecutionId,
      LangLockIds.EventId,
      LangLockCorrelation.CorrelationId,
      LangLockCorrelation.CausationId,
      LangLockCorrelation.RootSessionId,
      LangLockCorrelation.SessionId,
      LangLockCorrelation.Principal,
      LangLockCorrelation.ProjectRef,
      LangLockCorrelation.TodoRef,
      LangLockCorrelation.OutputRef,
      LangLockCorrelation.ManifestRef,
      LangLockValues.PolicyVersion,
      LangLockValues.ConfigVersion,
      LangLockValues.SchemaVersion,
      LangLockValues.Sequence,
      LangLockValues.AdvisoryCount,
      LangLockValues.ExceptionCount,
      LangLockTextValues.DisplayName,
      LangLockTextValues.Reason,
      LangLockTextValues.Timestamp,
      LangLockTextValues.TraceId,
      LangLockTextValues.SpanId,
      LangLockTextValues.Enabled,
      LangLockTextValues.OverrideAuthorized,
      LangLockTextValues.HardFloor,
      LangLockEnums.Scope,
      LangLockEnums.Origin,
      LangLockEnums.EnforcementMode,
      LangLockEnums.Axis,
      LangLockEnums.PathKind,
      LangLockEnums.ConfidenceBucket,
      LangLockEnums.DetectorProvenance,
      LangLockEnums.RemediationStatus,
      LangLockEnums.ExceptionCategory,
      LangLockEnumsEvent.EventClass,
      LangLockEnumsEvent.EventSource,
      LangLockEnumsEvent.ActorKind,
      LangLockEnumsEvent.AuditAction,
      LangLockEventTypes.LangLockEventType,
      LangLockAllowlist.AllowlistEntry,
      LangLockPolicy.PolicyIdentity,
      LangLockPolicy.PolicyLanguage,
      LangLockPolicy.PolicyAuthority,
      LangLockPolicy.LangLockPolicy,
      LangLockEffective.EffectiveLanguage,
      LangLockEffective.EffectiveAuthority,
      LangLockEffective.EffectiveConfig,
      LangLockExecution.StampLanguage,
      LangLockExecution.StampProvenance,
      LangLockExecution.StampTree,
      LangLockExecution.ExecutionStamp,
      LangLockDetection.DetectorClassification,
      LangLockDetection.DetectorResult,
      LangLockDetection.AdvisoryRecord,
      LangLockException.ExceptionAuthority,
      LangLockException.ExceptionEntry,
      LangLockException.ExceptionManifest,
      LangLockConfig.ConfigLanguage,
      LangLockConfig.ConfigAuthority,
      LangLockConfig.LangLockConfig,
      LangLockEnvelope.EventKind,
      LangLockEnvelope.ActorContext,
      LangLockEnvelope.Ordering,
      LangLockEnvelope.Delivery,
      LangLockEnvelope.LangLockEnvelope,
      LangLockEvents.PolicyDetail,
      LangLockEvents.OverrideDetail,
      LangLockEvents.ExceptionDetail,
      LangLockEvents.InjectionDetail,
      LangLockEvents.AdvisoryDetail,
      LangLockEvents.ResolutionDetail,
      LangLockEvents.LangLockPolicySetEvent,
      LangLockEvents.LangLockPolicyResetEvent,
      LangLockEvents.LangLockOverrideAuthorizedEvent,
      LangLockEvents.LangLockOverrideDeniedEvent,
      LangLockEvents.LangLockExceptionRegisteredEvent,
      LangLockEvents.LangLockExceptionRevokedEvent,
      LangLockEvents.LangLockPolicyInjectedEvent,
      LangLockEvents.LangLockPolicyReappliedEvent,
      LangLockEvents.LangLockEnvelopeStampedEvent,
      LangLockEvents.LangLockAdvisoryFlaggedEvent,
      LangLockEvents.LangLockAdvisoryAcknowledgedEvent,
      LangLockEvents.LangLockAdvisorySuppressedEvent,
      LangLockEvents.LangLockDetectorUnknownEvent,
      LangLockEvents.LangLockResolutionRetainedEvent,
      LangLockEvents.LangLockUnknownEvent,
      LangLockEvents.LangLockEvent,
      OutputSpoolIds.GroupId,
      OutputSpoolIds.OutputRef,
      OutputSpoolIds.ChannelId,
      OutputSpoolIds.ProcessId,
      OutputSpoolIds.RootSessionId,
      OutputSpoolIds.SessionId,
      OutputSpoolIds.ProjectId,
      OutputSpoolIds.EventId,
      OutputSpoolIds.LeaseId,
      OutputSpoolIds.HolderRef,
      OutputSpoolCorrelation.CorrelationId,
      OutputSpoolCorrelation.CausationId,
      OutputSpoolCorrelation.Principal,
      OutputSpoolCorrelation.SecretRef,
      OutputSpoolCorrelation.TranscriptRef,
      OutputSpoolCorrelation.TodoRef,
      OutputSpoolCorrelation.HandoffRef,
      OutputSpoolCorrelation.NotificationRef,
      OutputSpoolCorrelation.RowTelemetryRef,
      OutputSpoolValues.ByteOffset,
      OutputSpoolValues.ByteLength,
      OutputSpoolValues.CommittedBytes,
      OutputSpoolValues.NextOffset,
      OutputSpoolValues.PageLimit,
      OutputSpoolValues.QueueDepthBytes,
      OutputSpoolValues.Sequence,
      OutputSpoolValues.SchemaVersion,
      OutputSpoolValues.Generation,
      OutputSpoolValues.Attempt,
      OutputSpoolTextValues.ContentType,
      OutputSpoolTextValues.IntegrityTag,
      OutputSpoolTextValues.LanguageTag,
      OutputSpoolTextValues.Reason,
      OutputSpoolTextValues.TraceId,
      OutputSpoolTextValues.SpanId,
      OutputSpoolTextValues.CaughtUp,
      OutputSpoolTextValues.Eof,
      OutputSpoolTextValues.Disposable,
      OutputSpoolEnums.Channel,
      OutputSpoolEnums.GroupState,
      OutputSpoolEnums.ActionScope,
      OutputSpoolEnums.QuotaScope,
      OutputSpoolEnums.DurabilityTier,
      OutputSpoolEnums.AdmissionFault,
      OutputSpoolEnums.ErrorCode,
      OutputSpoolEnums.CursorState,
      OutputSpoolEnums.RetentionEdgeKind,
      OutputSpoolEnums.LegalHoldState,
      OutputSpoolEnumsEvent.EventClass,
      OutputSpoolEnumsEvent.EventSource,
      OutputSpoolEnumsEvent.ActorKind,
      OutputSpoolEnumsEvent.Visibility,
      OutputSpoolEnumsEvent.SettlementOutcome,
      OutputSpoolEnumsEvent.LanguageProvenance,
      OutputSpoolEnumsEvent.ExportEncoding,
      OutputSpoolEventTypes.OutputEventType,
      OutputSpoolCursor.OutputCursor,
      OutputSpoolCursor.CursorStatus,
      OutputSpoolPage.PageRange,
      OutputSpoolPage.ReadRequest,
      OutputSpoolPage.ReadPage,
      OutputSpoolStat.StatProvenance,
      OutputSpoolStat.OutputStat,
      OutputSpoolPreview.PreviewText,
      OutputSpoolPreview.BoundedPreview,
      OutputSpoolQuota.QuotaDescriptor,
      OutputSpoolRetention.TtlMs,
      OutputSpoolRetention.RetentionLease,
      OutputSpoolRetention.ReferenceEdge,
      OutputSpoolRetention.RetentionDescriptor,
      OutputSpoolGroup.OutputGroupRef,
      OutputSpoolGroup.GroupLineage,
      OutputSpoolGroup.GroupDurability,
      OutputSpoolGroup.GroupSettlement,
      OutputSpoolGroup.OutputGroup,
      OutputSpoolChannel.ChannelContent,
      OutputSpoolChannel.ChannelState,
      OutputSpoolChannel.ChannelProvenance,
      OutputSpoolChannel.OutputChannel,
      OutputSpoolEnvelope.EventKind,
      OutputSpoolEnvelope.EventSubject,
      OutputSpoolEnvelope.Ordering,
      OutputSpoolEnvelope.Delivery,
      OutputSpoolEnvelope.OutputEnvelope,
      OutputSpoolEvents.SealDetail,
      OutputSpoolEvents.AbortDetail,
      OutputSpoolEvents.SettlementDetail,
      OutputSpoolEvents.ReconcileDetail,
      OutputSpoolEvents.FenceDetail,
      OutputSpoolEvents.RetentionEventDetail,
      OutputSpoolEvents.AdmissionEventDetail,
      OutputSpoolEvents.OutputChannelSealedEvent,
      OutputSpoolEvents.OutputChannelAbortedEvent,
      OutputSpoolEvents.OutputSettlementRecordedEvent,
      OutputSpoolEvents.OutputReconciledEvent,
      OutputSpoolEvents.OutputGenerationFencedEvent,
      OutputSpoolEvents.OutputGroupReleasedEvent,
      OutputSpoolEvents.OutputGroupReclaimedEvent,
      OutputSpoolEvents.OutputChunkAppendedEvent,
      OutputSpoolEvents.OutputBackpressureSignalledEvent,
      OutputSpoolEvents.OutputAdmissionDegradedEvent,
      OutputSpoolEvents.OutputUnknownEvent,
      OutputSpoolEvents.OutputEvent,
      OutputSpoolAdmin.MigrationState,
      OutputSpoolAdmin.ExportRequest,
      OutputSpoolAdmin.ShareRequest,
      SemanticIds.ProviderProfileId,
      SemanticIds.ModelDescriptorId,
      SemanticIds.BindingId,
      SemanticIds.AgentDocId,
      SemanticIds.SkillDocId,
      SemanticIds.SkillChunkId,
      SemanticIds.GenerationId,
      SemanticIds.CollectionAliasId,
      SemanticIds.ProjectId,
      SemanticIds.EventId,
      SemanticIds.ToolDocId,
      SemanticIds.ToolRef,
      SemanticIds.McpServerRef,
      SemanticRefs.ProviderRef,
      SemanticRefs.ModelRef,
      SemanticRefs.ParentSkillId,
      SemanticRefs.AgentRef,
      SemanticRefs.SkillRef,
      SemanticRefs.PermissionRef,
      SemanticRefs.SecretRef,
      SemanticRefs.HeaderRef,
      SemanticRefs.OperatorRef,
      SemanticRefs.OutputRef,
      SemanticCorrelation.CorrelationId,
      SemanticCorrelation.CausationId,
      SemanticCorrelation.TraceId,
      SemanticCorrelation.SpanId,
      SemanticCorrelation.DecisionId,
      SemanticValues.BindingVersion,
      SemanticValues.SchemaVersion,
      SemanticValues.ConfigVersion,
      SemanticValues.Dimension,
      SemanticValues.Sequence,
      SemanticValues.ByteOffset,
      SemanticValues.ByteLimit,
      SemanticValues.ChunkIndex,
      SemanticValues.ChunkOverlap,
      SemanticValues.TopK,
      SemanticValues.ChunkBudget,
      SemanticValues.TokenBudget,
      SemanticValues.BatchSize,
      SemanticValues.VectorCount,
      SemanticValues.LatencyBudgetMs,
      SemanticValues.CacheTtlMs,
      SemanticValues.Score,
      SemanticValues.RerankScore,
      SemanticValues.DenseScore,
      SemanticValues.SparseScore,
      SemanticValues.Confidence,
      SemanticValues.FreshnessAgeMs,
      SemanticTextValues.Name,
      SemanticTextValues.DisplayName,
      SemanticTextValues.Description,
      SemanticTextValues.BaseUrl,
      SemanticTextValues.LanguageTag,
      SemanticTextValues.Tag,
      SemanticTextValues.ModeTag,
      SemanticTextValues.DegradedReason,
      SemanticTextValues.Timestamp,
      SemanticTextValues.Reason,
      SemanticTextValues.ContentHash,
      SemanticTextValues.ConfigHash,
      SemanticTextValues.Fingerprint,
      SemanticTextValues.Enabled,
      SemanticTextValues.Available,
      SemanticTextValues.Normalized,
      SemanticTextValues.InsecureAllowed,
      SemanticTextValues.Truncated,
      SemanticCollections.TagSet,
      SemanticCollections.LanguageSet,
      SemanticCollections.AgentRefSet,
      SemanticCollections.SkillRefSet,
      SemanticCollections.HeaderRefSet,
      SemanticCollections.AliasRefSet,
      SemanticEnums.Slot,
      SemanticEnums.TransportProfile,
      SemanticEnums.RerankProfile,
      SemanticEnums.EndpointMode,
      SemanticEnums.Consistency,
      SemanticEnums.CapabilityKind,
      SemanticEnums.Metric,
      SemanticEnums.IndexType,
      SemanticEnums.ModelSource,
      SemanticEnums.ValidationStatus,
      SemanticEnumsState.BindingState,
      SemanticEnumsState.GenerationState,
      SemanticEnumsState.DegradationGap,
      SemanticEnumsState.RetrievalMode,
      SemanticEnumsState.ResidencyProfile,
      SemanticEnumsState.TlsPolicy,
      SemanticEnumsState.Collection,
      SemanticEnumsState.ScopeKind,
      SemanticEnumsState.Visibility,
      SemanticEnumsState.RoleKind,
      SemanticEnumsState.ToolSource,
      SemanticEnumsState.JsonSchemaType,
      SemanticEnumsState.ToolRetrievalMode,
      SemanticEnumsState.ToolSurface,
      SemanticEnumsState.ToolTriggerSource,
      SemanticEnumsEvent.EventClass,
      SemanticEnumsEvent.EventSource,
      SemanticEnumsEvent.ActorKind,
      SemanticEnumsEvent.CutoverOutcome,
      SemanticEnumsEvent.FreshnessBucket,
      SemanticEventTypes.SemanticEventType,
      SemanticProviderProfile.ProviderVersion,
      SemanticProviderProfile.ProviderIdentity,
      SemanticProviderProfile.ProviderTransport,
      SemanticProviderProfile.ProviderCredentials,
      SemanticProviderProfile.ProviderAudit,
      SemanticProviderProfile.SemanticProviderProfile,
      SemanticModelDescriptor.ModelIdentity,
      SemanticModelDescriptor.CapabilityKindSet,
      SemanticModelDescriptor.ModelLimits,
      SemanticModelDescriptor.ModelCapability,
      SemanticModelDescriptor.ModelValidation,
      SemanticModelDescriptor.SemanticModelDescriptor,
      SemanticBinding.BindingRefs,
      SemanticBinding.CapabilityContract,
      SemanticBinding.BindingSelection,
      SemanticBinding.BindingGeneration,
      SemanticBinding.BindingStatus,
      SemanticBinding.SemanticModelBinding,
      SemanticDocuments.DocIdentity,
      SemanticDocuments.DocScope,
      SemanticDocuments.DocAvailability,
      SemanticDocuments.AgentClassification,
      SemanticDocuments.AgentTaxonomy,
      SemanticDocuments.SkillDescriptor,
      SemanticDocuments.SkillTaxonomy,
      SemanticDocuments.SkillCompat,
      SemanticDocuments.SkillCost,
      SemanticDocuments.ChunkPosition,
      SemanticDocuments.ChunkBodyRef,
      SemanticDocuments.AgentDoc,
      SemanticDocuments.SkillDoc,
      SemanticDocuments.SkillChunkDoc,
      SemanticToolDescriptor,
      SemanticToolParameter,
      SemanticToolParameterProjection,
      SemanticToolDoc,
      SemanticToolSurfaceConfig,
      SemanticToolSearchConfig,
      SemanticProfile.QueryFingerprint,
      SemanticProfile.TaskProfile,
      SemanticRetrieval.RetrievalRequest,
      SemanticRetrieval.ScoreComponents,
      SemanticRetrieval.ScoreProvenance,
      SemanticRetrieval.SemanticScore,
      SemanticRetrieval.Candidate,
      SemanticRetrieval.CandidateList,
      SemanticRetrieval.DegradationOutcome,
      SemanticRetrieval.RetrievalResult,
      SemanticIndexGeneration.SemanticIndexGeneration,
      SemanticIndexGeneration.CollectionAlias,
      SemanticEnvelope.EventKind,
      SemanticEnvelope.EventSubject,
      SemanticEnvelope.Ordering,
      SemanticEnvelope.Delivery,
      SemanticEnvelope.SemanticEnvelope,
      SemanticEvents.BindingSelectionDetail,
      SemanticEvents.CutoverDetail,
      SemanticEvents.IndexMutationDetail,
      SemanticEvents.ReconcileDetail,
      SemanticEvents.GenerationDetail,
      SemanticEvents.DegradationDetail,
      SemanticEvents.ProbeDetail,
      SemanticEvents.StateChangeDetail,
      SemanticEvents.SemanticBindingSelectedEvent,
      SemanticEvents.SemanticBindingCutoverEvent,
      SemanticEvents.SemanticBindingRolledBackEvent,
      SemanticEvents.SemanticIndexUpsertedEvent,
      SemanticEvents.SemanticIndexTombstonedEvent,
      SemanticEvents.SemanticIndexReconciledEvent,
      SemanticEvents.SemanticGenerationBuiltEvent,
      SemanticEvents.SemanticGenerationCutoverEvent,
      SemanticEvents.SemanticGenerationRetiredEvent,
      SemanticEvents.SemanticRetrievalDegradedEvent,
      SemanticEvents.SemanticProviderProbedEvent,
      SemanticEvents.SemanticBindingStateChangedEvent,
      SemanticEvents.SemanticEvent,
      // Feature 008 — MCP client lifecycle and content-plane schema identifiers (T001-T009).
      McpIds.ServerId,
      McpIds.ConnectionId,
      McpIds.ToolName,
      McpIds.PromptName,
      McpIds.RequestId,
      McpIds.TaskId,
      McpIds.ProgressToken,
      McpIds.SubscriptionId,
      McpIds.EventId,
      McpRefs.SecretRef,
      McpRefs.HeaderRef,
      McpRefs.OperatorRef,
      McpRefs.PermissionRef,
      McpRefs.OutputRef,
      McpRefs.GroupId,
      McpRefs.ProcessId,
      McpRefs.ProjectId,
      McpRefs.SessionId,
      McpRefs.CorrelationId,
      McpRefs.CausationId,
      McpValues.SchemaVersion,
      McpValues.Sequence,
      McpValues.PageIndex,
      McpValues.PageSize,
      McpValues.MaxPages,
      McpValues.ByteLength,
      McpValues.AttemptCount,
      McpValues.DurationMillis,
      McpValues.Progress,
      McpValues.Total,
      McpTextValues.ServerName,
      McpTextValues.ProtocolVersion,
      McpTextValues.Reason,
      McpTextValues.DisplayLabel,
      McpTextValues.Cursor,
      McpTextValues.ProvenanceLabel,
      McpTextValues.Title,
      McpTextValues.RedactedText,
      McpTextValues.Timestamp,
      McpUri.ResourceUri,
      McpUri.ResourceTemplateUri,
      McpUri.UriScheme,
      McpUri.RootUri,
      McpUri.MimeType,
      McpPolicy.Enabled,
      McpPolicy.Capable,
      McpPolicy.Hint,
      McpPolicy.Supported,
      McpPolicy.OperatorSurfaced,
      McpPolicy.SensitiveBlocked,
      McpPolicy.PolicyOptin,
      McpPolicy.RateLimited,
      McpPolicy.Active,
      McpPolicy.Coalesced,
      McpEnums.TransportKind,
      McpEnums.TrustProfile,
      McpEnums.OutputSchemaMode,
      McpEnums.ContentKind,
      McpEnums.CancelWirePath,
      McpEnums.CapabilityGap,
      McpEnums.TaskSupport,
      McpEnums.LogLevel,
      McpEnums.ProvenanceClass,
      McpEnumsState.ServerStatus,
      McpEnumsState.ConnectionState,
      McpEnumsState.TerminalBranch,
      McpEnumsState.CatalogState,
      McpEnumsState.SubscriptionState,
      McpEnumsState.TaskStatus,
      McpEnumsState.ResourceUpdatePolicy,
      McpEnumsState.CallOutcome,
      McpEnumsState.CancelOutcome,
      McpEnumsEvent.EventClass,
      McpEnumsEvent.EventSource,
      McpEnumsEvent.ActorKind,
      McpEnumsEvent.Visibility,
      McpEnumsEvent.CatalogKind,
      McpEventTypes.McpEventType,
      McpExperimental.ExperimentalFlag,
      McpExperimental.FlagState,
      McpExperimental.ContentStreamCapability,
      McpExperimental.FlagSet,
      McpCollections.HeaderRefSet,
      McpCollections.SchemeSet,
      McpCollections.RootUriList,
      McpCollections.MimeTypeSet,
      McpCollections.ToolNameList,
      McpCollections.SecretRefList,
      McpCapability.ToolsCapability,
      McpCapability.ResourcesCapability,
      McpCapability.PromptsCapability,
      McpCapability.LoggingCapability,
      McpCapability.ExperimentalCapability,
      McpCapability.NegotiatedCapabilities,
      McpConnection.ReconnectPosture,
      McpConnection.SessionResume,
      McpConnection.McpConnection,
      McpAllowlist.UriAllowlist,
      McpAllowlist.MimeAllowlist,
      McpSpoolDescriptor.BoundedPreview,
      McpSpoolDescriptor.ContentItem,
      McpSpoolDescriptor.ResourceLink,
      McpSpoolDescriptor.ContentItemList,
      McpSpoolDescriptor.ContentEnvelope,
      McpSpoolDescriptor.McpCallOutput,
      McpSpoolDescriptor.McpReadOutput,
      McpEnvelope.EventKind,
      McpEnvelope.EventSubject,
      McpEnvelope.Ordering,
      McpEnvelope.Delivery,
      McpEnvelope.McpEventEnvelope,
      McpEventsServer.ServerStatusDetail,
      McpEventsServer.CapabilitiesChangedDetail,
      McpEventsServer.CatalogChangedDetail,
      McpEventsServer.McpServerStatusEvent,
      McpEventsServer.McpCapabilitiesChangedEvent,
      McpEventsServer.McpToolsChangedEvent,
      McpEventsServer.McpResourcesChangedEvent,
      McpEventsResource.ResourceUpdatedDetail,
      McpEventsResource.SubscriptionDetail,
      McpEventsResource.McpResourceUpdatedEvent,
      McpEventsResource.McpSubscriptionSubscribedEvent,
      McpEventsResource.McpSubscriptionUnsubscribedEvent,
      McpEventsCall.CallSettledDetail,
      McpEventsCall.CallCancelledDetail,
      McpEventsCall.TaskSettledDetail,
      McpEventsCall.McpCallSettledEvent,
      McpEventsCall.McpCallCancelledEvent,
      McpEventsCall.McpTaskSettledEvent,
      McpEventsLive.CallStartedDetail,
      McpEventsLive.CallProgressDetail,
      McpEventsLive.CancelRequestedDetail,
      McpEventsLive.McpCallStartedEvent,
      McpEventsLive.McpCallProgressEvent,
      McpEventsLive.McpCallCancelRequestedEvent,
      McpEventsLog.TaskStatusDetail,
      McpEventsLog.LogDetail,
      McpEventsLog.McpTaskStatusEvent,
      McpEventsLog.McpLogEvent,
      McpEvents.McpEvent,
    ].map((schema) => schema.ast.annotations?.identifier)

    expect(identifiers.every((identifier) => typeof identifier === "string")).toBe(true)
    expect(new Set(identifiers).size).toBe(identifiers.length)
  })

  test("current source avoids Any and mutable contract wrappers", async () => {
    const files = [...new Bun.Glob("*.ts").scanSync(new URL("../src", import.meta.url).pathname)].filter(
      (file) => !file.endsWith("-v1.ts"),
    )
    const source = await Promise.all(
      files.map((file) => Bun.file(new URL(`../src/${file}`, import.meta.url)).text()),
    ).then((values) => values.join("\n"))

    expect(source).not.toContain("Schema.Any")
    expect(source).not.toContain("Schema.mutable")
  })
})
