import { describe, expect, test } from "bun:test"
import { Schema } from "effect"
import { Agent } from "../src/agent"
import { FileSystem } from "../src/filesystem"
import { Admission } from "../src/lifecycle/admission"
import { Cancel } from "../src/lifecycle/cancel"
import { CorrelationIds } from "../src/lifecycle/correlation-ids"
import { Enums } from "../src/lifecycle/enums"
import { EnumsObservation } from "../src/lifecycle/enums-observation"
import { Envelope } from "../src/lifecycle/envelope"
import { Events as LifecycleEvent } from "../src/lifecycle/events"
import { Ids as LifecycleIds } from "../src/lifecycle/ids"
import { Observation } from "../src/lifecycle/observation"
import { Row } from "../src/lifecycle/process-row"
import { RowParts } from "../src/lifecycle/process-row-parts"
import { TodoEvents } from "../src/lifecycle/todo-events"
import { Usage } from "../src/lifecycle/usage"
import { UsageValues } from "../src/lifecycle/usage-values"
import { Values } from "../src/lifecycle/values"
import { Watchdog } from "../src/lifecycle/watchdog"
import { Model } from "../src/model"
import { Project } from "../src/project"
import { Pty } from "../src/pty"
import { Question } from "../src/question"
import { Budget } from "../src/routing/budget"
import { Capability } from "../src/routing/capability"
import { RoutingConfig } from "../src/routing/config"
import { Decision } from "../src/routing/decision"
import { Events } from "../src/routing/events"
import { Ids } from "../src/routing/ids"
import { Session } from "../src/session"
import { SessionEvent } from "../src/session-event"
import { SessionTodo } from "../src/session-todo"
import { Config as TelemetryConfig } from "../src/telemetry/config"
import { SmartState } from "../src/tui/smart-state"
import { Correlation as JobsCorrelation } from "../src/jobs/correlation"
import { Definition as JobsDefinition } from "../src/jobs/definition"
import { Enums as JobsEnums } from "../src/jobs/enums"
import { EnumsEvent as JobsEnumsEvent } from "../src/jobs/enums-event"
import { EnumsNotification as JobsEnumsNotification } from "../src/jobs/enums-notification"
import { Envelope as JobsEnvelope } from "../src/jobs/envelope"
import { Events as JobsEvents } from "../src/jobs/events"
import { EventTypes as JobsEventTypes } from "../src/jobs/event-types"
import { Ids as JobsIds } from "../src/jobs/ids"
import { Notification as JobsNotification } from "../src/jobs/notification"
import { Occurrence as JobsOccurrence } from "../src/jobs/occurrence"
import { Reconciliation as JobsReconciliation } from "../src/jobs/reconciliation"
import { Schedule as JobsSchedule } from "../src/jobs/schedule"
import { TextValues as JobsTextValues } from "../src/jobs/text-values"
import { Values as JobsValues } from "../src/jobs/values"
import { optional } from "../src/schema"

describe("contract hygiene", () => {
  test("optional properties preserve transformations and omit undefined while encoding", () => {
    const Value = Schema.Struct({ value: optional(Schema.FiniteFromString) })
    expect(Schema.decodeUnknownSync(Value)({ value: "1" })).toEqual({ value: 1 })
    expect(Schema.encodeSync(Value)({ value: 1 })).toEqual({ value: "1" })
    expect(Schema.encodeSync(Value)({ value: undefined })).toEqual({})
  })

  test("todo status and priority preserve arbitrary strings", () => {
    const decode = Schema.decodeUnknownSync(SessionTodo.Info)
    expect(decode({ content: "ship", status: "waiting", priority: "urgent" })).toEqual({
      content: "ship",
      status: "waiting",
      priority: "urgent",
    })
  })

  test("current ID constructors expose create", () => {
    expect(Question.ID.create()).toStartWith("que_")
    expect(Pty.ID.create()).toStartWith("pty_")
  })

  test("reusable public identifiers are stable and unique", () => {
    const identifiers = [
      Agent.Color,
      FileSystem.Submatch,
      Model.Ref,
      Model.Capabilities,
      Model.Cost,
      Model.Api,
      Project.Icon,
      Project.Commands,
      Project.Time,
      Project.Info,
      Pty.Info,
      Session.ListAnchor,
      Ids.Reason,
      Ids.Requirement,
      Ids.Version,
      Capability.ToolCallDimensions,
      Capability.Identity,
      Capability.Confidence,
      Capability.Assessment,
      Capability.Freshness,
      Capability.Record,
      Capability.Mismatch,
      Decision.GatePassed,
      Decision.CandidateRejected,
      Decision.TieBreakApplied,
      Decision.FallbackAttempted,
      Decision.Offline,
      Decision.GateResult,
      Decision.GateList,
      Decision.SkillList,
      Decision.CandidateIdentity,
      Decision.CandidateProfile,
      Decision.CandidateOutcome,
      Decision.CandidateRecord,
      Decision.RankedCandidate,
      Decision.RankingList,
      Decision.AuthContextSnapshot,
      Decision.ExpectedTools,
      Decision.InputStructure,
      Decision.InputRisk,
      Decision.InputConcurrency,
      Decision.DecisionInputs,
      Decision.DecisionOutput,
      Decision.DecisionContext,
      Decision.DecisionClassification,
      Decision.DecisionSelection,
      Decision.DecisionEvaluation,
      Decision.DecisionAccounting,
      Decision.DecisionLifecycle,
      Decision.RoutingDecision,
      Events.DecisionCorrelation,
      Events.EventClassification,
      Events.EventSelection,
      Events.DispatchLineage,
      Events.DispatchFanout,
      Events.TodoPointer,
      Events.EvidenceRefs,
      Events.RoutingDecisionEvent,
      Events.RoutingFallbackEvent,
      Events.HierarchyDispatchEvent,
      Events.HierarchyValidationEvent,
      Events.HierarchyEscalationEvent,
      Events.CapabilityMismatchEvent,
      Events.TodoInitializedEvent,
      Events.TodoCompletionBlockedEvent,
      Events.RoutingEvent,
      Budget.Limits,
      Budget.Concurrency,
      Budget.Retrieval,
      Budget.Cost,
      Budget.Resilience,
      Budget.Policy,
      Budget.Scope,
      Budget.PolicySnapshot,
      Budget.ConsumptionThroughput,
      Budget.ConsumptionConcurrency,
      Budget.ConsumptionRetrieval,
      Budget.ConsumptionCost,
      Budget.ConsumptionResilience,
      Budget.Consumption,
      RoutingConfig.Activation,
      RoutingConfig.Models,
      RoutingConfig.Enforcement,
      RoutingConfig.Info,
      TelemetryConfig.SecretRef,
      TelemetryConfig.ExportTarget,
      TelemetryConfig.TelemetryConfig,
      SmartState.Active,
      SmartState.Inactive,
      Admission.CapacitySignals,
      Admission.TokenBucketState,
      Admission.AdmissionBucket,
      Admission.AdmissionResult,
      Cancel.RootCancelScope,
      Cancel.CancelRequestRecord,
      CorrelationIds.CorrelationId,
      CorrelationIds.CausationId,
      CorrelationIds.DecisionId,
      CorrelationIds.TurnId,
      CorrelationIds.AgentName,
      CorrelationIds.ModelId,
      CorrelationIds.ProviderName,
      CorrelationIds.VariantName,
      CorrelationIds.TodoRef,
      CorrelationIds.TodoVersion,
      Enums.ProcessState,
      Enums.LifecycleEventType,
      Enums.EventClass,
      Enums.TerminalReason,
      Enums.SettlementState,
      Enums.Visibility,
      Enums.AgentKind,
      Enums.ActorKind,
      EnumsObservation.UsageProvenance,
      EnumsObservation.UsageSource,
      EnumsObservation.ActivityKind,
      EnumsObservation.HierarchyRole,
      EnumsObservation.ValidationOutcome,
      EnumsObservation.AnomalyKind,
      EnumsObservation.CancelOutcome,
      EnumsObservation.WatchdogOutcome,
      EnumsObservation.AdmissionScope,
      EnumsObservation.AdmissionDecision,
      EnumsObservation.ObservationKind,
      Envelope.EventKind,
      Envelope.TreeIdentity,
      Envelope.ProcessIdentity,
      Envelope.Ordering,
      Envelope.Delivery,
      Envelope.Delegation,
      Envelope.HierarchyCorrelation,
      Envelope.HierarchyContext,
      Envelope.LifecycleEnvelope,
      LifecycleEvent.AdmissionDetail,
      LifecycleEvent.HandoffEndpoint,
      LifecycleEvent.HandoffDetail,
      LifecycleEvent.TerminalDetail,
      LifecycleEvent.WatchdogDetail,
      LifecycleEvent.ToolActivityDetail,
      LifecycleEvent.SteerDetail,
      LifecycleEvent.ReconcileDetail,
      LifecycleEvent.AdmittedEvent,
      LifecycleEvent.ParentAttachedEvent,
      LifecycleEvent.ProcessCreatedEvent,
      LifecycleEvent.StartedEvent,
      LifecycleEvent.HandoffEvent,
      LifecycleEvent.ReconciledEvent,
      LifecycleEvent.CompletedEvent,
      LifecycleEvent.FailedEvent,
      LifecycleEvent.CancelledEvent,
      LifecycleEvent.ZombieDetectedEvent,
      LifecycleEvent.OwnerLostEvent,
      LifecycleEvent.QueuedEvent,
      LifecycleEvent.WaitingEvent,
      LifecycleEvent.PromotedEvent,
      LifecycleEvent.ExtendedEvent,
      LifecycleEvent.TurnStartedEvent,
      LifecycleEvent.TurnEndedEvent,
      LifecycleEvent.TurnFailedEvent,
      LifecycleEvent.UnknownEvent,
      LifecycleEvent.SteerRequestedEvent,
      LifecycleEvent.SteerAcceptedEvent,
      LifecycleEvent.SteerRejectedEvent,
      LifecycleEvent.CancelRequestedEvent,
      LifecycleEvent.CancellingEvent,
      LifecycleEvent.ToolCalledEvent,
      LifecycleEvent.ToolSettledEvent,
      LifecycleEvent.LifecycleEvent,
      LifecycleIds.TaskId,
      LifecycleIds.ProcessId,
      LifecycleIds.ParentProcessId,
      LifecycleIds.RootProcessId,
      LifecycleIds.SessionId,
      LifecycleIds.ParentSessionId,
      LifecycleIds.RootSessionId,
      LifecycleIds.RuntimeInstanceId,
      LifecycleIds.LeaseId,
      LifecycleIds.EventId,
      Observation.ObservationScope,
      Observation.ObservationFilter,
      Observation.AnomalyRecord,
      Observation.ObservationResult,
      Row.RowIdentity,
      Row.RowStatus,
      Row.RowHierarchy,
      Row.ProcessRow,
      RowParts.RowRelations,
      RowParts.RowOwnership,
      RowParts.RowGraph,
      RowParts.RowLineage,
      RowParts.RowClassification,
      RowParts.RowModel,
      RowParts.RowProfile,
      RowParts.RowUsage,
      RowParts.RowOutcome,
      RowParts.RowTelemetry,
      RowParts.RowAccounting,
      TodoEvents.TodoPointer,
      TodoEvents.TodoCounts,
      TodoEvents.TodoUpdatedEvent,
      TodoEvents.TodoCompletedEvent,
      TodoEvents.TodoFailedEvent,
      TodoEvents.TodoCancelledEvent,
      TodoEvents.TodoStaleEvent,
      TodoEvents.TodoRehydratedEvent,
      TodoEvents.TodoHandoffAttachedEvent,
      TodoEvents.TodoEvent,
      Usage.TokenBreakdown,
      Usage.UsageProvenanceMark,
      Usage.LiveUsage,
      UsageValues.TokenCount,
      UsageValues.CostUsd,
      UsageValues.ElapsedMs,
      UsageValues.DurationMs,
      UsageValues.TokensPerSecond,
      UsageValues.TraceId,
      UsageValues.SpanId,
      UsageValues.OutputRef,
      UsageValues.Cursor,
      UsageValues.Confidence,
      Values.Sequence,
      Values.Attempt,
      Values.Generation,
      Values.SchemaVersion,
      Values.DelegationDepth,
      Values.FanoutCount,
      Values.ItemCount,
      Values.Reason,
      Values.Description,
      Values.ActivityLabel,
      Watchdog.WatchdogLease,
      Watchdog.ZombieAssessment,
      Watchdog.ReconcileRecord,
      JobsIds.JobDefinitionId,
      JobsIds.ScheduleId,
      JobsIds.OccurrenceId,
      JobsIds.ProcessId,
      JobsIds.RootProcessId,
      JobsIds.SessionId,
      JobsIds.ParentSessionId,
      JobsIds.RootSessionId,
      JobsIds.NotificationId,
      JobsIds.EventId,
      JobsCorrelation.CorrelationId,
      JobsCorrelation.CausationId,
      JobsCorrelation.DecisionId,
      JobsCorrelation.TurnId,
      JobsCorrelation.Principal,
      JobsCorrelation.SecretRef,
      JobsCorrelation.PayloadRef,
      JobsCorrelation.OutputRef,
      JobsCorrelation.ProjectRef,
      JobsCorrelation.TodoRef,
      JobsValues.Sequence,
      JobsValues.Attempt,
      JobsValues.Generation,
      JobsValues.SchemaVersion,
      JobsValues.Version,
      JobsValues.DeadlineMs,
      JobsValues.TimeoutMs,
      JobsValues.RetryBudget,
      JobsValues.Priority,
      JobsValues.ScheduleLagMs,
      JobsTextValues.JobName,
      JobsTextValues.JobDescription,
      JobsTextValues.ActionTarget,
      JobsTextValues.BoundedSummary,
      JobsTextValues.Reason,
      JobsTextValues.TraceId,
      JobsTextValues.SpanId,
      JobsTextValues.Enabled,
      JobsTextValues.PermissionSet,
      JobsSchedule.CronExpression,
      JobsSchedule.IanaTimezone,
      JobsSchedule.MinimumIntervalMs,
      JobsSchedule.NominalDueTime,
      JobsSchedule.CronSchedule,
      JobsEnums.RegistrationState,
      JobsEnums.RegistrationIntent,
      JobsEnums.OccurrenceState,
      JobsEnums.MisfirePolicy,
      JobsEnums.OverlapPolicy,
      JobsEnums.ActionType,
      JobsEnums.Scope,
      JobsEnums.CapabilitySurface,
      JobsEnums.ReconcileOutcome,
      JobsEnums.EventClass,
      JobsEnumsEvent.JobSource,
      JobsEnumsEvent.ActorKind,
      JobsEnumsEvent.Visibility,
      JobsEnumsNotification.NotificationType,
      JobsEnumsNotification.NotificationPriority,
      JobsEnumsNotification.NotificationSource,
      JobsEnumsNotification.DeliveryState,
      JobsEnumsNotification.AckState,
      JobsEnumsNotification.DeliveryAction,
      JobsEnumsNotification.SafeBoundary,
      JobsEventTypes.JobEventType,
      JobsEnvelope.EventKind,
      JobsEnvelope.OccurrenceIdentity,
      JobsEnvelope.TreeIdentity,
      JobsEnvelope.Ordering,
      JobsEnvelope.Delivery,
      JobsEnvelope.JobEnvelope,
      JobsDefinition.SecretRefList,
      JobsDefinition.DefinitionIdentity,
      JobsDefinition.DefinitionSchedule,
      JobsDefinition.DefinitionPolicy,
      JobsDefinition.DefinitionExecution,
      JobsDefinition.DefinitionAuthorization,
      JobsDefinition.JobDefinition,
      JobsReconciliation.ScheduleRegistration,
      JobsReconciliation.OccurrenceReconcile,
      JobsReconciliation.RegistrationReconcile,
      JobsOccurrence.IdempotencyKey,
      JobsOccurrence.OccurrenceLineage,
      JobsOccurrence.OccurrenceExecution,
      JobsOccurrence.OccurrenceStatus,
      JobsOccurrence.JobOccurrence,
      JobsNotification.NotificationRouting,
      JobsNotification.NotificationDescriptor,
      JobsNotification.NotificationTiming,
      JobsNotification.NotificationContent,
      JobsNotification.NotificationState,
      JobsNotification.NotificationEnvelope,
      JobsEvents.DefinitionDetail,
      JobsEvents.RegistrationDetail,
      JobsEvents.TriggerDetail,
      JobsEvents.MisfireDetail,
      JobsEvents.OverlapDetail,
      JobsEvents.ExecutionDetail,
      JobsEvents.RetryDetail,
      JobsEvents.NotificationDetail,
      JobsEvents.ReconcileDetail,
      JobsEvents.JobDefinitionCreatedEvent,
      JobsEvents.JobDefinitionUpdatedEvent,
      JobsEvents.JobDefinitionEnabledEvent,
      JobsEvents.JobDefinitionDisabledEvent,
      JobsEvents.JobDefinitionDeletedEvent,
      JobsEvents.JobRegisteredEvent,
      JobsEvents.JobUnregisteredEvent,
      JobsEvents.JobRescheduledEvent,
      JobsEvents.JobTriggerDueEvent,
      JobsEvents.JobOccurrenceClaimedEvent,
      JobsEvents.JobTriggeredEvent,
      JobsEvents.JobMisfiredEvent,
      JobsEvents.JobSkippedEvent,
      JobsEvents.JobCoalescedEvent,
      JobsEvents.JobQueuedEvent,
      JobsEvents.JobAdmittedEvent,
      JobsEvents.JobNotificationEnqueuedEvent,
      JobsEvents.JobNotificationDeliveredEvent,
      JobsEvents.JobNotificationAcknowledgedEvent,
      JobsEvents.JobNotificationExpiredEvent,
      JobsEvents.JobExecutionStartedEvent,
      JobsEvents.JobExecutionCompletedEvent,
      JobsEvents.JobExecutionFailedEvent,
      JobsEvents.JobExecutionCancelledEvent,
      JobsEvents.JobExecutionTimedOutEvent,
      JobsEvents.JobRetryScheduledEvent,
      JobsEvents.JobOverlapRejectedEvent,
      JobsEvents.JobOverlapReplacedEvent,
      JobsEvents.JobReconciledEvent,
      JobsEvents.JobUnknownEvent,
      JobsEvents.JobEvent,
    ].map((schema) => schema.ast.annotations?.identifier)

    expect(identifiers.every((identifier) => typeof identifier === "string")).toBe(true)
    expect(new Set(identifiers).size).toBe(identifiers.length)
  })

  test("current source avoids Any and mutable contract wrappers", async () => {
    const files = [...new Bun.Glob("*.ts").scanSync(new URL("../src", import.meta.url).pathname)].filter(
      (file) => !file.endsWith("-v1.ts"),
    )
    const source = await Promise.all(
      files.map((file) => Bun.file(new URL(`../src/${file}`, import.meta.url)).text()),
    ).then((values) => values.join("\n"))

    expect(source).not.toContain("Schema.Any")
    expect(source).not.toContain("Schema.mutable")
  })
})
